language: python
python:
      - "2.6"
      - "2.7"
      - "3.2"
      - "3.3"
      - "3.4"
      - "3.5"
      - "3.5-dev" # 3.5 development branch
      - "nightly" # currently points to 3.6-dev
before_script:
      - ssh-keygen -f id_rsa -t rsa -N ''
      - cat ~/.ssh/id_rsa >> ~/.ssh/authorized_keys/
      - echo -e "Host localhost\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: python test.py
